#!/bin/sh
# Generates vectors.S: one entry point per interrupt, so trap() knows which
# fired. The cpu pushes an error code for 8, 10..14 and 17.

set -eu

echo "# generated by vectors.sh - do not edit"
echo "# handlers"
echo ".globl alltraps"

i=0
while [ $i -lt 256 ]; do
	echo ".globl vector$i"
	echo "vector$i:"
	case $i in
	8|10|11|12|13|14|17) ;;
	*) echo "  pushq \$0" ;;
	esac
	echo "  pushq \$$i"
	echo "  jmp alltraps"
	i=$((i + 1))
done

echo ""
echo "# vector table"
echo ".data"
echo ".globl vectors"
echo "vectors:"

i=0
while [ $i -lt 256 ]; do
	echo "  .quad vector$i"
	i=$((i + 1))
done
